{{- range prepend (.Values.workloads.namespaces | default list) .Values.workloads.default_namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eirini
  namespace: {{ . }}
automountServiceAccountToken: false
{{- end }}
