{{- if .Values.workloads.create_namespaces }}
{{- range prepend (.Values.workloads.namespaces | default list) .Values.workloads.default_namespace }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/enforce: restricted
{{- end }}
{{- end }}
