---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eirini-controller
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eirini-controller-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - eirini-controller
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - create
  - update
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - leases
  verbs:
  - get
  - create
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eirini-controller-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: eirini-controller-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eirini-controller
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eirini-controller-cluster-role
rules:
- apiGroups:
  - eirini.cloudfoundry.org
  resources:
  - lrps
  - tasks
  verbs:
  - watch
  - list
  - get
- apiGroups:
  - eirini.cloudfoundry.org
  resources:
  - lrps/status
  verbs:
  - patch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
  - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eirini-controller-cluster-rolebinding
roleRef:
  kind: ClusterRole
  name: eirini-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: eirini-controller
  namespace: {{ .Release.Namespace }}
