---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: eirini-x-mutating-hook
webhooks:
- name: instance-index-env-injector.eirini.cloudfoundry.org
  objectSelector:
    matchLabels:
      workloads.cloudfoundry.org/source-type: APP
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]
    scope: "Namespaced"
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: eirini-webhooks
    caBundle: {{ .Values.webhooks.ca_bundle }}
  admissionReviewVersions: ["v1beta1"]
  sideEffects: None
  timeoutSeconds: 10

