---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: eirini-resource-validator-hook
  {{- if not .Values.webhooks.ca_bundle }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/webhook-cert
  {{- end }}
webhooks:
- name: resource-validator.eirini.cloudfoundry.org
  rules:
  - apiGroups: ["eirini.cloudfoundry.org"]
    apiVersions: ["v1"]
    operations: ["UPDATE"]
    resources: ["lrps"]
    scope: "Namespaced"
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: eirini-webhooks
      path: "/lrps"
    {{- if .Values.webhooks.ca_bundle }}
    caBundle: {{ .Values.webhooks.ca_bundle }}
    {{- end }}
  admissionReviewVersions: ["v1beta1"]
  sideEffects: None
  timeoutSeconds: 10

