---
apiVersion: v1
kind: Service
metadata:
  name: eirini-webhooks
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      targetPort: 8443
      protocol: TCP
      name: https
  selector:
    name: eirini-controller

