{{- if not .Values.webhooks.ca_bundle }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  commonName: eirini-webhooks.{{ .Release.Namespace }}.svc
  dnsNames:
  - eirini-webhooks.{{ .Release.Namespace }}.svc.cluster.local
  - eirini-webhooks.{{ .Release.Namespace }}.svc
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: {{ .Values.webhooks.certs_secret_name }}
{{- end }}
